vjezba3:vjezba3.o funkcije.o
	gcc -Wall vjezba3.o -o vjezba3
vjezba3.o:vjezba3.c
	gcc -Wall -c vjezba3.c
funkcije.o:funkcije.c
	gcc -Wall -c funkcije.c
clear:
	rm *.o *.txt vjezba3 
run:vjezba3
	./vjezba3 file.txt fajl.txt

